trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - sportcar
    - test

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - sportcar
    - test

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python3.7:
      python.version: '3.7'
    Python3.8:
      python.version: '3.8'
    Python3.10:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install poetry
  displayName: 'Instalar poetry'

- script: |
    poetry config virtualenvs.create false
    poetry update && poetry install
  displayName: 'Dependencias'

- script: |
    invoke test
  displayName: 'Tests'
