name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check del repositorio
      uses: actions/checkout@v2
    - name: Build the Docker image
      #uses: docker/login-action@v1
      env:
        DOCKER_USER: $
        DOCKER_PASSWORD: $
        
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build
      run: docker build . --file Dockerfile
      
    - name: Push
      run: docker push $
