name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check del repositorio
      uses: actions/checkout@v2
    - name: Login en dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/sport-car
      
    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/sport-car
